import torch
from client_utils.general_utils import set_seed

set_seed()


def accumulate_batches(generate_batch_fn, dataset_size, batch_size):
    """
    Accumulate batches generated by generate_batch_fn until reaching dataset_size samples.
    """

    synthetic_data = []
    generated = 0
    while generated < dataset_size:
        current_batch_size = min(batch_size, dataset_size - generated)
        batch_data = generate_batch_fn(current_batch_size)
        synthetic_data.append(batch_data)
        generated += current_batch_size
    return torch.cat(synthetic_data, dim=0)


def predict_classes(model, data, device, batch_size=256):
    """
    Return predicted class labels for the given data using the model on the specified device, processing in batches.
    """
    model.eval()
    predicted_classes = []
    with torch.no_grad():
        for i in range(0, len(data), batch_size):
            batch = data[i:i+batch_size].to(device)
            outputs = model(batch)
            preds = torch.argmax(outputs, dim=1)
            predicted_classes.append(preds)
    return torch.cat(predicted_classes) if predicted_classes else torch.tensor([], device=device)


def filter_by_prediction(model, data, labels, target_class, device, batch_size=256):
    """
    Return the subset of data and labels for which the model's predictions match the target_clas.
    """
    predicted_classes = predict_classes(model, data, device, batch_size)
    mask = predicted_classes == target_class
    print(f"Total samples: {data.shape[0]}, Matched samples: {mask.sum().item()}")
    return data[mask], labels[mask]